import React,{useMemo,useState} from 'react';
import {DataComponent,Dropdown,Button,useDataApp} from '../../data-app-public.jsx';
import {PartyName} from './PartyName.jsx';
import {MeanSeats} from './MeanSeats.jsx';
import {useMethodSimulation} from './useMethodSimulation.js';
import {COMPARISON_METHODS,methodComparisons,extremeAt,numberLabel,dateLabel,downloadRows} from './transparency-data.js';
import {MethodGuide} from './MethodGuide.jsx';
import './transparency-pages.css';

const labels={min:'הנמוך בשורה',max:'הגבוה בשורה'};
function MethodHeaders(){return COMPARISON_METHODS.map(m=><th scope="col" key={m.id} className={m.id==='robust'?'tp-our-method':undefined} data-method={m.id}>{m.name}<small className={m.id==='robust'?'tp-our-badge':undefined}>{m.qualifier}</small></th>);}
function NumericCell({values,index,children,ourMethod=false,...props}){
 const extreme=extremeAt(values,index);
 return <td {...props} className={[extreme?'tp-extreme tp-'+extreme:'',ourMethod?'tp-our-method':''].filter(Boolean).join(' ')} data-extreme={extreme||undefined}>{children??<bdi>{numberLabel(values[index])}%</bdi>}{extreme&&<small className="tp-rank">{extreme==='max'?'▲':'▼'} {labels[extreme]}</small>}</td>;
}
export function MethodDataPage({input,config,onOpenPollData,onOpenTrends}){
 const {queries}=useDataApp(),[metric,setMetric]=useState('support'),[partiesOpen,setPartiesOpen]=useState(false);
 const comparison=useMemo(()=>{try{return {rows:methodComparisons(input,config),error:''};}catch(e){return {rows:[],error:e.message};}},[input,config]);
 const computed=useMethodSimulation(input,config,COMPARISON_METHODS.map(m=>m.id),metric==='seats'&&partiesOpen);
 const results=computed.results,seatError=computed.error;
 const sourceIds=['polls','model_input','weight_presets','calibration','turnout_baseline','agreements','poll_correlation_profile'].filter(id=>queries[id]);
 const bind={queryId:'polls',queryIds:sourceIds,sourceRows:queries.polls.rows,sourceRowsByQuery:Object.fromEntries(sourceIds.map(id=>[id,queries[id].rows]))};
 const weights=input.current.polls.map(poll=>({poll,values:comparison.rows.map(({combined})=>{const i=combined.polls.findIndex(p=>p.id===poll.id);return i<0?0:100*(combined.policyWeights??combined.weights)[i];})}));
 const weightRows=weights.flatMap(({poll,values})=>COMPARISON_METHODS.map((method,i)=>({סקר:poll.publisher,סוקר:poll.pollster,'מזהה סקר':poll.id,תאריך:poll.date,גישה:method.name,'סוג גישה':method.qualifier,'משקל אפקטיבי (%)':values[i]??null,'דמיון בין סקרים מופעל':config.pollCorrelationEnabled===true,'נתונים נכון ל':input.current.asOf})));
 const partyRows=input.parties.map((party,j)=>({party,values:COMPARISON_METHODS.map((method,i)=>metric==='support'?(comparison.rows[i]?.combined.center[j]??NaN)*100:results?.[method.id]?.parties.find(p=>p.id===party.id)?.mean??NaN)}));
 const exportPartyRows=partyRows.flatMap(({party,values})=>COMPARISON_METHODS.map((method,i)=>{const stats=results?.[method.id]?.parties.find(p=>p.id===party.id);return {מפלגה:party.name,גישה:method.name,'סוג גישה':method.qualifier,'דמיון בין סקרים מופעל':config.pollCorrelationEnabled===true,מדד:metric==='support'?'תמיכה משוקללת לפני השתתפות (%)':(config.iterations===1?'מנדטים בהדמיה אחת':'תוחלת מנדטים במודל'),ערך:Number.isFinite(values[i])?values[i]:null,'95% תחתון':metric==='seats'?stats?.meanCI?.[0]??null:null,'95% עליון':metric==='seats'?stats?.meanCI?.[1]??null:null,'מספר הרצות':metric==='seats'?config.iterations:null,'זרע הרצה':metric==='seats'?config.seed:null,'נתונים נכון ל':input.current.asOf};}));
 const loading=metric==='seats'&&!results&&!seatError;
 return <section className="transparency-page" data-transparency-page="method-data">
  <MethodGuide input={input} config={config} onOpenPollData={onOpenPollData} onOpenTrends={onOpenTrends}/>
  <p className="mg-comparison-summary">רוצים לבדוק איך גישות אחרות משנות את התוצאה? פתחו את ההשוואות למטה. כולן משתמשות באותו מאגר ובהגדרות התרחיש הנוכחיות.</p>
  {comparison.error?<p role="alert">{comparison.error}</p>:<>
   <details className="mg-comparison-details"><summary>השוואת משקלי הסקרים בין גישות — לחצו לפתיחה</summary><div className="mg-comparison-body">
   <DataComponent id="method-poll-weight-matrix" title="כמה משקל מקבל כל סקר?" variant="card" kind="table" {...bind} displayRows={weightRows} description="משקלים אפקטיביים ומנורמלים בכל שיטה על הסקרים הפעילים; מכפילים ידניים מופעלים בסוף. כל עמודה מסתכמת ב־100%.">
    <div className="tp-toolbar"><p>{comparison.rows[0]?.combined.polls.length} מתוך {input.current.polls.length} סקרים פעילים · כל עמודה = 100%</p><Button onClick={()=>downloadRows('method-poll-weights-'+input.current.asOf+'.csv',weightRows)}>הורדת טבלת המשקלים CSV</Button></div>
    <div className="tp-scroll" tabIndex={0} role="region" aria-label="השוואת משקלי הסקרים"><table className="tp-table tp-methods" data-reviewed-rows data-method-weights><thead><tr><th scope="col">סקר / מכון</th><MethodHeaders/></tr></thead><tbody>{weights.map(({poll,values})=><tr key={poll.id} data-poll-id={poll.id}><th scope="row">{poll.publisher}<small>{poll.pollster}</small><small>{dateLabel(poll.date)}</small></th>{values.map((v,i)=><td key={i} data-method={COMPARISON_METHODS[i].id} className={COMPARISON_METHODS[i].id==='robust'?'tp-our-method':undefined}><bdi>{numberLabel(v)}%</bdi>{v===0&&<small>לא משתתף בשקלול</small>}</td>)}</tr>)}</tbody><tfoot><tr><th>סך הכול</th>{COMPARISON_METHODS.map((m,i)=><td key={m.id} className={m.id==='robust'?'tp-our-method':undefined}><bdi>{numberLabel(weights.reduce((s,row)=>s+row.values[i],0))}%</bdi></td>)}</tr></tfoot></table></div>
   </DataComponent>
   </div></details>
   <details className="mg-comparison-details" onToggle={event=>setPartiesOpen(event.currentTarget.open)}><summary>השוואת תמיכה ומנדטים בין גישות — לחצו לפתיחה</summary><div className="mg-comparison-body">
   <DataComponent id="method-party-value-matrix" title="השוואת המפלגות לפי גישת השקלול" variant="card" kind="table" {...bind} displayRows={exportPartyRows} description="השוואת התמיכה המשוקללת ששוחזרה במודל, או תוחלת המנדטים מסימולציות המודל. הצבעים משווים ערכים בתוך אותה מפלגה, ואינם טוענים להבדל מובהק סטטיסטית.">
    <div className="tp-toolbar"><Dropdown triggerClassName="filter-trigger e-content-select" contentClassName="election-select-menu" label="מדד להשוואה" showLabel value={metric} choices={['support','seats']} choiceLabels={{support:'תמיכה משוקללת (%)',seats:config.iterations===1?'מנדטים בהדמיה אחת':'תוחלת מנדטים ± 95%'}} onChange={setMetric}/><Button disabled={loading||(metric==='seats'&&!!seatError)} onClick={()=>downloadRows('method-party-'+metric+'-'+input.current.asOf+'.csv',exportPartyRows)}>הורדת השוואת המפלגות CSV</Button></div>
    <p className="tp-legend"><span className="tp-legend-max">▲ ירוק: הגבוה בשורה</span><span className="tp-legend-min">▼ אדום: הנמוך בשורה</span><span>המסגרת הסגולה מזהה את המיזוג שלנו. שוויון מלא נשאר ללא צבע קיצון. הצבע מציין סדר, לא מובהקות.</span></p>
    <p className="tp-note">{metric==='support'?'אחוזי התמיכה כוללים שחזור מקומי ממנדטים, לפני התאמות הצבעה, אחוז החסימה ובאדר–עופר. שינוי בשיעורי ההצבעה אינו משנה טבלה זו.':config.iterations===1?'בכל גישה מוצגת הדמיית בחירות אחת באותם תנאים. זו אינה תוחלת, ואין כאן רווח סמך.':'תוחלת המנדטים מחושבת באותם תנאי הצבעה, טעות סקרים, חסימה והסכמי עודפים בכל השיטות. ± הוא רווח סמך 95% לשגיאת אמידת הממוצע מההרצות בלבד.'}</p>
    {loading?<p role="status">מחשב את הגישות והמיזוג שלנו… <progress value={computed.progress} max="1" aria-label="התקדמות השוואת המנדטים"/></p>:seatError&&metric==='seats'?<p role="alert">{seatError}</p>:<div className="tp-scroll" tabIndex={0} role="region" aria-label="השוואת המפלגות בין הגישות"><table className="tp-table tp-methods" data-reviewed-rows data-method-parties data-metric={metric}><thead><tr><th scope="col">מפלגה</th><MethodHeaders/></tr></thead><tbody>{partyRows.filter(row=>row.party.ballot!==false).map(({party,values})=><tr key={party.id} data-party-row={party.id}><th scope="row"><PartyName party={party} bloc={config.partyBlocs[party.id]}/></th>{values.map((v,i)=><NumericCell key={i} values={values} index={i} ourMethod={COMPARISON_METHODS[i].id==='robust'} data-method={COMPARISON_METHODS[i].id}>{metric==='seats'?<MeanSeats stats={results[COMPARISON_METHODS[i].id].parties.find(p=>p.id===party.id)} iterations={config.iterations}/>:<bdi>{numberLabel(v)}%</bdi>}</NumericCell>)}</tr>)}</tbody>{metric==='support'&&<tfoot>{partyRows.filter(row=>row.party.ballot===false).map(({party,values})=><tr key={party.id}><th>{party.name}<small>יתרה שלא זוהתה כרשימה</small></th>{values.map((v,i)=><td key={i} className={COMPARISON_METHODS[i].id==='robust'?'tp-our-method':undefined}><bdi>{numberLabel(v)}%</bdi></td>)}</tr>)}<tr><th>סך הכול כולל היתרה</th>{COMPARISON_METHODS.map((m,i)=><td key={m.id} className={m.id==='robust'?'tp-our-method':undefined}><bdi>{numberLabel(partyRows.reduce((s,row)=>s+row.values[i],0))}%</bdi></td>)}</tr></tfoot>}</table></div>}
    {metric==='seats'&&<p className="tp-note">{config.iterations.toLocaleString('he-IL')} הרצות לכל שיטה · זרע {config.seed} · כל עמודה מחושבת מחדש לפי ההגדרות המשותפות.</p>}
   </DataComponent>
   </div></details>
  </>}
  <details className="mg-comparison-details"><summary>פירוט הגישות וההבדל מהפרויקטים המקוריים</summary><div className="mg-comparison-body">
  <p className="tp-note">אלה יישומים במודל שלנו, לא טבלת התחזיות הרשמית של פרויקטי המקור. השיטות משנות את משקלם של אותם סקרים, ולא מוסיפות מדגמים. השקלול השמרני שלנו הוא אחת האפשרויות להשוואה; ברירת המחדל באתר היא דיוק היסטורי.</p>
  <DataComponent id="method-provenance-register" title="מה לקחנו מכל גישה?" variant="card" kind="custom" queryId="weight_presets" sourceRows={queries.weight_presets.rows} displayRows={COMPARISON_METHODS.map(m=>({גישה:m.name,סיווג:m.qualifier,הסבר:m.description,מקורות:input.weightPresets.methods[m.id].sourceUrls.join(' ')}))}>
   <div className="tp-method-notes">{COMPARISON_METHODS.map(m=>{const preset=input.weightPresets.methods[m.id];return <div key={m.id} className={m.id==='robust'?'tp-our-explanation':undefined}><h3>{m.name} <small>— {m.qualifier}</small></h3><p>{m.description}</p>{m.id==='robust'&&<p>בסיס שווה בהגדרות הנוכחיות: {numberLabel(100*(config.robustShrinkage??.25),0)}%. הגישות המשתתפות ומשקליהן נקבעים בבקרים למעלה. הקישורים מתעדים את גישות הקלט, ולא מפרסמים או מאמתים את נוסחת המיזוג שלנו.</p>}{m.id==='gilead'&&<p>מכון היעד כרגע: {config.gileadTarget==='next_data'?'NEXT DATA':'דיירקט פולס'}.</p>}{m.id==='rosner'&&<p>בקירוב הנוכחי: זמן מחצית חיים {comparison.rows.find(row=>row.method.id==='rosner')?.combined.contributions[0]?.parameters.halfLifeDays??config.rosnerHalfLifeDays??config.halfLifeDays??14} ימים, סף חריגות {config.rosnerOutlierCutoffPP??2} נקודות אחוז. גודל מדגם חסר מוחלף ב־500 כהנחה.</p>}<small>תאריך מידע על המשקלים: {dateLabel(preset.asOf??preset.retrievedAt??input.weightPresets.asOf)}</small><p>{preset.sourceUrls.map((url,i)=><a className="tp-source-link" key={url} href={url} target="_blank" rel="noreferrer">{m.id==='robust'?'מקור לגישת קלט':'מקור'} {i+1}</a>)}</p></div>;})}</div>
  </DataComponent>
  </div></details>
 </section>;
}
