import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createSimulation} from '../dashboard/src/content/dashboard/model/simulate.js';
import {normalizeSiteScenario} from '../dashboard/src/content/dashboard/site-scenario-policy.js';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const out='artifacts/site-v2-2026-10-09';fs.mkdirSync(out,{recursive:true});
const before=read(out+'/before/dashboard/src/data.json'),now=read('dashboard/src/data.json'),manifest=read(out+'/before/manifest.json');
assert.equal(before.id,now.id);
const input=Object.fromEntries(before.queries.model_input.rows.map(row=>[row.key,row.value]));
const config=Object.fromEntries(before.queries.model_configuration.rows.map(row=>[row.key,row.value]));
const old={...Object.fromEntries(before.queries.simulation_summary.rows.map(row=>[row.key,row.value])),parties:before.queries.simulation_results.rows};
const run=c=>{const job=createSimulation(input,normalizeSiteScenario(c));while(job.done<c.iterations)job.step(1000);return job.finish();};
const result=run(config);
const exact=['iterations','parties','blocHist','blocStats','reportingGroups','coalitionHist','coalitionStats','counts','probabilities','probabilityCI','meanBallots','meanValid','meanTurnout','worlds','nEffective','methodWeights','pointProbabilities','expectedVotesRounded','turnout','checks'];
for(const key of exact)assert.deepEqual(result[key],old[key],key);
for(const [name,hash] of Object.entries(manifest.files).filter(([name])=>name.startsWith('data/')))assert.equal(sha(name),hash,name);
for(const query of ['polls','poll_history','model_input','calibration','weight_presets','verified_party_trends','verified_party_trends_without_channel14','poll_correlation_profile'])assert.deepEqual(now.queries[query].rows,before.queries[query].rows,query);
assert.deepEqual(run({...config,signalNoiseEnabled:true}).parties,result.parties);
assert.deepEqual(run({...config,weightMode:'signal_noise'}).parties,result.parties);
assert.equal(result.checks.eachWorld120,true);assert.equal(result.checks.blocPartition120,true);
const report={status:'PASS',siteVersion:2,newPollCount:0,appId:now.id,previousPublicHead:manifest.publishedHead,exactNumericalCollections:exact,iterations:config.iterations,unchangedSourceFiles:Object.entries(manifest.files).filter(([name])=>name.startsWith('data/')).map(([path,sha256])=>({path,sha256})),disabledRetiredFeatureThroughImport:true,default:{weightMode:config.weightMode,includeChannel14:config.includeChannel14,pollCorrelationEnabled:config.pollCorrelationEnabled,signalNoiseEnabled:result.config.signalNoiseEnabled},results:{blocs:result.blocStats,majority:result.probabilities},snapshotSha256:sha('dashboard/src/data.json')};
fs.writeFileSync(out+'/regression.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:'PASS',numericalCollections:exact.length,sourceFiles:report.unchangedSourceFiles.length,legacyImportDisabled:true}));
