import React,{useMemo,useState} from 'react';
import {DataComponent,Dropdown,Button,useDataApp} from '../../data-app-public.jsx';
import {PartyName} from './PartyName.jsx';
import {MeanSeats} from './MeanSeats.jsx';
import {combineForecast} from './model/forecast.js';
import {WEIGHTING_LABELS} from './WeightingControl.jsx';
import {dateLabel,fieldworkLabel,reportedSupport,numberLabel,downloadRows} from './transparency-data.js';
import './transparency-pages.css';
import {SurveyDocumentReview} from './SurveyDocumentReview.jsx';

export function PollDataPage({input,config,result,busy=false,error}){
 const {queries}=useDataApp(),[measure,setMeasure]=useState('seats');
 const polls=input.current.polls,parties=input.parties.filter(p=>p.ballot!==false);
 const conservative=useMemo(()=>{try{return {combined:combineForecast(input,config),error:''};}catch(e){return {combined:null,error:e.message};}},[input,config]);
 const simulation={loading:busy,error},robustResult=!busy&&!error?result:null;
 const methodLabel=WEIGHTING_LABELS[config.weightMode]??config.weightMode;
 const supportModelled=id=>robustResult?robustResult.parties.find(p=>p.id===id)?.hasModelledSupport!==false:Number(conservative.combined?.center[input.parties.findIndex(p=>p.id===id)])>0;
 const derivedRows=parties.map(party=>{const index=input.parties.findIndex(p=>p.id===party.id),stats=robustResult?.parties.find(p=>p.id===party.id),modelled=supportModelled(party.id);return {מפלגה:party.name,'מזהה מפלגה':party.id,'סוג רשומה':'תוצאת מודל — התרחיש שנבחר',גישה:methodLabel,'אומדן תמיכה נפרד':modelled?'יש אומדן':'אין אומדן','תמיכה מחושבת לפני השתתפות (%)':modelled&&conservative.combined?100*conservative.combined.center[index]:null,'מנדטים במודל':measure==='seats'&&modelled?stats?.mean??null:null,'פירוש המנדטים':measure==='seats'?(config.iterations===1?'הדמיה אחת':'תוחלת מכל ההרצות'):null,'95% תחתון':measure==='seats'&&modelled?stats?.meanCI?.[0]??null:null,'95% עליון':measure==='seats'&&modelled?stats?.meanCI?.[1]??null:null,'מספר הרצות':measure==='seats'?config.iterations:null,'זרע הרצה':measure==='seats'?config.seed:null,'נתונים נכון ל':input.current.asOf,'שגיאת חישוב':conservative.error||(measure==='seats'?simulation.error:'')||null};});

 const allRows=useMemo(()=>parties.flatMap(party=>polls.map(poll=>({מפלגה:party.name,'מזהה מפלגה':party.id,מפרסם:poll.publisher,סוקר:poll.pollster,'מזהה סקר':poll.id,'תאריך הסקר במאגר':poll.date,'תחילת עבודת שדה':poll.fieldworkStart??null,'סיום עבודת שדה':poll.fieldworkEnd??null,'נבדק בתאריך':poll.checkedAt??null,'גודל מדגם':poll.sampleSize??null,'מנדטים בקלט':poll.seats?.[party.id]??null,'תמיכה שפורסמה (%)':reportedSupport(poll,party.id).value,'אחוז נקוב המשמש במודל (%)':poll.percentages?.[party.id]??null,'תיאור תמיכה':reportedSupport(poll,party.id).label,מקור:poll.sourceUrl,'סוג מקור':poll.sourceTier,'נתון נוסף שלא מוזג':(poll.additionalPublishedPercentages??[]).filter(x=>x.partyId===party.id).map(x=>x.pct+'% — '+x.reasonNotMerged).join('; ')}))),[input]);
 const displayRows=[...allRows.map(row=>({...row,'סוג רשומה':'נתון מקור'})),...derivedRows];
 const bind={queryId:'polls',queryIds:['polls','model_input'],sourceRows:queries.polls.rows,sourceRowsByQuery:{polls:queries.polls.rows,model_input:queries.model_input.rows}};
 return <section className="transparency-page" data-transparency-page="poll-data">
  <p className="tp-freshness"><strong>עדכון הנתונים: {dateLabel(input.current.asOf)}</strong><span>{polls.length} סקרים במאגר · פרסום: {dateLabel([...polls].sort((a,b)=>a.date.localeCompare(b.date))[0]?.date)} עד {dateLabel([...polls].sort((a,b)=>b.date.localeCompare(a.date))[0]?.date)}</span><span>כל נתון מוצג נכון לתאריך הבדיקה; העדכון התקופתי מתפרסם לאחר אימות.</span></p>
  <DataComponent id="source-poll-matrix" title="נתוני הסקרים שעליהם מבוסס המודל" variant="card" kind="table" {...bind} displayRows={displayRows} description="קלט הסקרים כפי שנאסף ונבדק בתאריך המצוין. עמודות הסקרים שומרות את נתוני המקור ואת החסרים. בעמודה המודגשת בנפרד מוצגים התמיכה ששוחזרה במודל או תוחלת המנדטים של התרחיש הפעיל שלכם, בנפרד מנתוני המקור.">
   <div className="tp-toolbar"><Dropdown triggerClassName="filter-trigger e-content-select" contentClassName="election-select-menu" label="מה להציג בטבלה" showLabel value={measure} choices={['seats','support']} choiceLabels={{seats:'מנדטים בסקר',support:'אחוזי תמיכה שפורסמו'}} onChange={setMeasure}/><Button disabled={measure==='seats'&&simulation.loading} onClick={()=>downloadRows('original-polls-with-selected-scenario-'+input.current.asOf+'.csv',displayRows)}>הורדת נתוני הסקרים CSV</Button></div>
   <p className="tp-note">מקף = נתון חסר או אומדן שלא חושב בנפרד; 0 מנדטים בסקר אינו 0% תמיכה. אחוזים חסרים נשארים חסרים בעמודות המקור. מוצג כל מאגר הבסיס, גם אם הסרתם סקר מהשקלול. אחוזי המקור אינם בהכרח וקטור התמיכה ששימש במודל: למשל, ב־NEXT DATA נשמר שחזור ממנדטים בגלל פער במכנה; ההסבר המלא בהערות הסקר.</p>
   <p className="tp-our-caption"><strong>התרחיש שבחרתם — {methodLabel}:</strong> {measure==='seats'?(config.iterations===1?'מנדטים בהדמיה אחת, ללא רווח סמך.':'תוחלת מנדטים ± רווח סמך 95% לשגיאת ההרצות, לאחר הצבעה, חסימה ובאדר–עופר.'):'אחוזי תמיכה מחושבים, כולל שחזור מקומי, לפני התאמות הצבעה וחלוקת מנדטים.'} העמודה מתעדכנת עם הגדרות התחזית בכל הדפים. היא תוצאת מודל, ואינה סקר נוסף. גישות אחרות אפשר להשוות בדף השיטות.</p>
   {(conservative.error||(measure==='seats'&&simulation.error))&&<p role="alert">התחזית אינה זמינה: {conservative.error||simulation.error}</p>}
   <div className="tp-scroll" tabIndex={0} role="region" aria-label="טבלת נתוני הסקרים; ניתן לגלול לרוחב"><table className="tp-table tp-polls-table" data-reviewed-rows data-poll-matrix><thead><tr><th scope="col">מפלגה</th><th scope="col" className="tp-our-method" data-method={config.weightMode}>התרחיש שבחרתם<small className="tp-our-badge">{methodLabel}</small><small>{measure==='support'?'תמיכה מחושבת (%)':config.iterations===1?'מנדטים בהדמיה':'תוחלת מנדטים ± 95%'}</small></th>{polls.map(p=><th scope="col" key={p.id}><span>{p.publisher}</span><small>{dateLabel(p.date)}</small><small>{p.pollster}</small></th>)}</tr></thead><tbody>{parties.map(party=><tr key={party.id}><th scope="row"><PartyName party={party} bloc={config.partyBlocs[party.id]}/></th><td className="tp-our-method" data-method={config.weightMode} data-party-id={party.id} data-model-supported={supportModelled(party.id)}>{!supportModelled(party.id)?<span>—<small>אין אומדן תמיכה נפרד</small></span>:measure==='support'?<bdi>{conservative.combined?numberLabel(100*conservative.combined.center[input.parties.findIndex(p=>p.id===party.id)])+'%':'—'}</bdi>:robustResult?<MeanSeats stats={robustResult.parties.find(p=>p.id===party.id)} iterations={config.iterations}/>:<span>{simulation.loading?'מחשב…':'—'}</span>}</td>{polls.map(poll=><td key={poll.id} data-poll-id={poll.id} data-party-id={party.id}><bdi>{measure==='seats'?(poll.seats?.[party.id]??'—'):reportedSupport(poll,party.id).label}</bdi>{measure==='seats'&&reportedSupport(poll,party.id).kind!=='missing'&&<small>{reportedSupport(poll,party.id).label} תמיכה</small>}</td>)}</tr>)}</tbody></table></div>
  </DataComponent>
  <DataComponent id="source-poll-register" title="תאריכים, מדגמים וקישורי מקור" variant="card" kind="table" {...bind} displayRows={polls.map(p=>({מפרסם:p.publisher,סוקר:p.pollster,תאריך:p.date,'עבודת שדה':fieldworkLabel(p),'נבדק בתאריך':p.checkedAt,'גודל מדגם':p.sampleSize,'סוג מקור':p.sourceTier,מקור:p.sourceUrl}))}>
   <div className="tp-scroll" tabIndex={0} role="region" aria-label="פרטי הסקרים"><table className="tp-table tp-register" data-reviewed-rows><thead><tr><th>הסקר</th><th>תאריך במאגר</th><th>עבודת שדה</th><th>מדגם</th><th>בדיקה אחרונה</th><th>מקור</th></tr></thead><tbody>{polls.map(p=><tr key={p.id}><th scope="row">{p.publisher}<small>{p.pollster}</small></th><td><bdi>{dateLabel(p.date)}</bdi></td><td>{fieldworkLabel(p)}</td><td>{p.sampleSize??'לא פורסם'}{p.sampleSizeSourceUrl&&<small><a href={p.sampleSizeSourceUrl} target="_blank" rel="noreferrer">מקור גודל המדגם</a></small>}</td><td><bdi>{dateLabel(p.checkedAt)}</bdi></td><td><a href={p.sourceUrl} target="_blank" rel="noreferrer">{p.sourceTier==='pollster-report'?'דוח הסוקר PDF':p.sourceTier==='original-publisher'?'פרסום מקורי':'מקור שנאסף'}</a><small>{p.sourceTier==='pollster-report'?'קובץ שנמסר ונבדק':p.sourceTier==='original-publisher'?'מקור ראשוני':'נתונים ממאגר משני'}</small></td></tr>)}</tbody></table></div>
   <p className="tp-note">תאריך הסקר במאגר ועבודת השדה אינם בהכרח אותו יום. תאריך הבדיקה מציין מתי הנתונים הוצלבו, ולא מתי נערך הסקר.</p>
   <div className="tp-poll-notes">{polls.map(p=><details key={p.id}><summary>הערות ומגבלות — {p.publisher}</summary><p>מכנה האחוזים: {p.percentageDenominator||'לא אומת'}.</p><p>שיטת הדגימה: {p.samplingMethod||'לא אומתה במאגר'}.</p>{p.undecidedPct!=null&&<p>מתלבטים שדווחו: {p.undecidedPct}%. אין להפחית אותם שוב בלי מכנה תואם.</p>}<ul>{(p.notes??[]).map((note,i)=><li key={i}>{note}</li>)}{(p.additionalPublishedPercentages??[]).map((extra,i)=><li key={'extra'+i}>נתון נוסף שלא מוזג: {extra.name} {extra.pct}% — {extra.reasonNotMerged}.</li>)}</ul><p>{(p.secondarySourceUrls??[]).map((url,i)=><a key={url} className="tp-source-link" href={url} target="_blank" rel="noreferrer">מקור הצלבה {i+1}</a>)}</p></details>)}</div>
  </DataComponent>
  <details className="e-disclosure tp-document-archive"><summary>ארכיון דוחות המקור והבדיקות</summary><SurveyDocumentReview review={input.current.documentReview}/></details>
 </section>;
}
